#
version: '3.2'
services:
  activemq:
    image: lewinc/activemq:latest-zulu-alpine
    hostname: activemq.local
    container_name: jmx-jms-demo-activemq
  interlok:
    image: adaptrislabs/interlok-jmx-jms:latest
    container_name: jmx-jms-demo-interlok
    hostname: interlok
    ports:
     - "8080:8080"
    environment:
      - JAVA_OPTS=-Dinterlok.mgmt.components=jetty:jmx -Dinterlok.jmxserviceurl=service:jmx:activemq:///tcp://activemq:61616?jmx.type=Topic&jmx.destination=myJmxTopic
    depends_on:
      - activemq
    links:
      - activemq:activemq
